### ISSUE TITLE
Add .list suffix for listing output

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-explorer-for-endevor#146] opened 2021-07-20 15:20 UTC

**Comment by nickImbirev** [comment] 2021-07-21 15:08
Hey @VitGottwald ! Thank you for submitting it! Can I ask you to take a look into #115? It seems like this issue can be a duplicate of that one. 

If yes - can I ask you to specify your suggestion there instead?

**Comment by jellypuno** [comment] 2021-10-05 11:53
Closing in favor of #115

**Closed by jellypuno** 2021-10-05 11:53 UTC
