### ISSUE TITLE
VSCode - Listing files have the type as a filename suffix

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#115] opened 2021-06-12 03:31 UTC
When I use the VSCode extension "Print listing" option the listing is retrieved with a filename suffix of the type name. In our case the suffix is ".cobb" which causes the listing to be viewed with COBOL highlighting on. This highlighting gives some unusual colouring.

Shouldn't the listing filename have .txt as it's suffix?

**Comment by venkatzhub** [comment] 2021-06-14 15:43
I guess it depends on "how unusual" the coloring is :). Is it coloring or trying to color the non-COBOL text as well? In some sense, it is good for the listing to color highlight the source where possible. Makes the reading of the listing easier, but if it is causing more confusion to the users than good, then yes, making the extension to be txt might be the way  to go.

**Comment by nickImbirev** [comment] 2021-07-02 14:44
I would say, that the issue is even bigger: right now, we are reading the file extensions from the Endevor, but they can be different, from one, that Code4z pack extensions are expected. It can be even null, so we will write the temp file or retrieved file without an extension at all.

I think we need to think about adding the TYPE of the element as a backup option in the file extensions. And I think, we can also show read-only listings in plain `.txt` format, because it is not editable content.

**Comment by nickImbirev** [comment] 2021-07-02 14:56
related to #7

**Comment by anton-brezina** [comment] 2021-10-05 11:53
If the Element has an Endevor Filename Suffix, we will use that. Else, We will check the Element type and use that as the file extension +*.lst (for print listing) and  *.prnt (for print element).

Example:
*.cbl.lst
*.hlasm.prnt

**Comment by nickImbirev** [comment] 2021-11-25 15:50
resolved within #181 PR

**Closed by nickImbirev** 2021-11-25 15:50 UTC
Labels: enhancement, Technical debt, minor, 21PI4
